In [25]:
import pandas as pd
import numpy as np
import os

In [2]:
#import the df that has all the SRAs with cgs

cgs_df=pd.read_csv(r'dap_subset_filtered.csv')
cgs_df

,Run,AGE,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,BREED,Bytes,...,Collection_Date,geo_loc_name_country,geo_loc_name_country_continent,geo_loc_name,dog_id,age_years,sample,sra,n_trials,prop_correct
0,SRR18483729,not applicable,WGS,293,3916878927,PRJNA800779,SAMN25333101,Model organism or animal,not applicable,1368569186,...,NaN,NaN,NaN,NaN,54567,7,3.102010e+13,SRR18483729,9,0.777778
1,SRR18483737,not applicable,WGS,295,2646060811,PRJNA800779,SAMN25333631,Model organism or animal,not applicable,972045291,...,NaN,NaN,NaN,NaN,83957,3,3.102010e+13,SRR18483737,9,0.777778
2,SRR18483738,not applicable,WGS,288,1757141014,PRJNA800779,SAMN25333499,Model organism or animal,not applicable,602949057,...,NaN,NaN,NaN,NaN,77689,9,3.102010e+13,SRR18483738,9,0.555556
3,SRR18483750,not applicable,WGS,293,1970980254,PRJNA800779,SAMN25332728,Model organism or animal,not applicable,672845987,...,NaN,NaN,NaN,NaN,38806,4,3.102010e+13,SRR18483750,6,0.833333
4,SRR18483755,not applicable,WGS,293,4125341982,PRJNA800779,SAMN25332724,Model organism or animal,not applicable,1415479323,...,NaN,NaN,NaN,NaN,38737,10,3.102010e+13,SRR18483755,8,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1879,SRR27935972,not applicable,WGS,293,2371756496,PRJNA800779,SAMN38875969,Model organism or animal,not applicable,857128365,...,not applicable,uncalculated,uncalculated,not applicable,119283,4,3.121110e+13,SRR27935972,9,0.666667
1880,SRR27935975,not applicable,WGS,294,2491915558,PRJNA800779,SAMN38875966,Model organism or animal,not applicable,919637072,...,not applicable,uncalculated,uncalculated,not applicable,109729,2,3.121110e+13,SRR27935975,9,0.777778
1881,SRR27935979,not applicable,WGS,295,3538704113,PRJNA800779,SAMN38875912,Model organism or animal,not applicable,1183874395,...,not applicable,uncalculated,uncalculated,not applicable,116731,1,3.121110e+13,SRR27935979,7,0.857143
1882,SRR27935984,not applicable,WGS,295,2495445881,PRJNA800779,SAMN38875908,Model organism or animal,not applicable,833484459,...,not applicable,uncalculated,uncalculated,not applicable,87040,8,3.121110e+13,SRR27935984,9,0.666667
1883,SRR27935992,not applicable,WGS,294,2940811965,PRJNA800779,SAMN38875939,Model organism or animal,not applicable,1034690305,...,not applicable,uncalculated,uncalculated,not applicable,119603,3,3.121110e+13,SRR27935992,7,0.571429

In [ ]:
#import cz_id df
#cz_id_df=pd.read_parquet(r'C:\Users\ssathees\dog-aging-project\combined_df.parquet')
cz_id_df

In [ ]:
#cz_id_df['sample'].nunique()

In [ ]:
#$cz_id_df['sample']=cz_id_df['sample'].astype('str')

In [ ]:
#cgs_df['sra']=cgs_df['sra'].astype('str')

In [ ]:
#species_cgs_df=pd.merge(cz_id_df,cgs_df,left_on='sample',right_on='sra',how='left')

In [3]:
species_cgs_df=pd.read_csv(r'C:\Users\ssathees\OneDrive - Fred Hutchinson Cancer Research Center\Documents\Downloads\species_cognitiveScoreSummary.csv')
species_cgs_df

C:\Users\ssathees\AppData\Local\Temp\ipykernel_6432\495303368.py:1: DtypeWarning: Columns (4,36,37,38,41,42,43,44,46,47,48,49,50,51,52,54,55,56,57,58,59,60,61,64,65,66,67,68,69,70,71,75,78) have mixed types. Specify dtype option on import or set low_memory=False.
  species_cgs_df=pd.read_csv(r'C:\Users\ssathees\OneDrive - Fred Hutchinson Cancer Research Center\Documents\Downloads\species_cognitiveScoreSummary.csv')

,tax_id,tax_level,genus_tax_id,name,common_name,category,is_phage,agg_score,max_z_score,nt_z_score,...,geo_loc_name_country,geo_loc_name_country_continent,geo_loc_name,dog_id,age_years,sample_y,sra,n_trials,prop_correct,performance_group
0,3119089,2,3119089,Fusibacillus,NaN,bacteria,False,NaN,NaN,NaN,...,NaN,NaN,NaN,83957.0,3.0,3.102006e+13,SRR18483737,9.0,0.777778,High
1,3044208,1,3119089,Fusibacillus kribbianus,NaN,bacteria,False,NaN,NaN,NaN,...,NaN,NaN,NaN,83957.0,3.0,3.102006e+13,SRR18483737,9.0,0.777778,High
2,3118928,2,3118928,Xylocopilactobacillus,NaN,bacteria,False,NaN,NaN,NaN,...,NaN,NaN,NaN,83957.0,3.0,3.102006e+13,SRR18483737,9.0,0.777778,High
3,2932183,1,3118928,Xylocopilactobacillus apis,NaN,bacteria,False,NaN,NaN,NaN,...,NaN,NaN,NaN,83957.0,3.0,3.102006e+13,SRR18483737,9.0,0.777778,High
4,3118803,2,3118803,Fontisubflavum,NaN,bacteria,False,NaN,NaN,NaN,...,NaN,NaN,NaN,83957.0,3.0,3.102006e+13,SRR18483737,9.0,0.777778,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092235,2969135,1,-202968741,Chloroherpetonaceae bacterium,NaN,bacteria,False,NaN,NaN,NaN,...,uncalculated,uncalculated,not applicable,87040.0,8.0,3.121105e+13,SRR27935984,9.0,0.666667,Low
2092236,-203031624,2,-203031624,non-genus-specific reads in family Desulfosarc...,NaN,bacteria,False,NaN,NaN,NaN,...,uncalculated,uncalculated,not applicable,87040.0,8.0,3.121105e+13,SRR27935984,9.0,0.666667,Low
2092237,3036616,1,-203031624,Desulfosarcinaceae bacterium,NaN,bacteria,False,NaN,NaN,NaN,...,uncalculated,uncalculated,not applicable,87040.0,8.0,3.121105e+13,SRR27935984,9.0,0.666667,Low
2092238,-203085335,2,-203085335,non-genus-specific reads in family Candidatus ...,NaN,bacteria,False,NaN,NaN,NaN,...,uncalculated,uncalculated,not applicable,87040.0,8.0,3.121105e+13,SRR27935984,9.0,0.666667,Low
2092239,3085339,1,-203085335,Candidatus Fermentithermobacillaceae bacterium,NaN,bacteria,False,NaN,NaN,NaN,...,uncalculated,uncalculated,not applicable,87040.0,8.0,3.121105e+13,SRR27935984,9.0,0.666667,Low

In [4]:
species_cgs_df['sample_x'].nunique()

99

In [5]:
species_cgs_df['prop_correct'].isna().sum()

np.int64(150826)

In [6]:
species_cgs_df['nt_rpm']=species_cgs_df['nt_rpm'].astype('float64')
species_cgs_df['nr_rpm']=species_cgs_df['nr_rpm'].astype('float64')

In [7]:
species_cgs_df['nt_rpm']=species_cgs_df['nt_rpm'].fillna(0)
species_cgs_df['nr_rpm']=species_cgs_df['nr_rpm'].fillna(0)

In [8]:
species_cgs_df['nt_nr_rpm']=species_cgs_df['nt_rpm']

In [9]:
species_cgs_df['nt_nr_rpm']=species_cgs_df['nt_nr_rpm'].fillna(species_cgs_df['nr_rpm'])

In [10]:
#add nt and nr

species_cgs_df['nt_nr_rpm_add']=species_cgs_df['nt_rpm'] + species_cgs_df['nr_rpm']

In [11]:
species_cgs_df['nt_nr_rpm_add']

0          7.781132
1          7.781132
2          0.972642
3          0.972642
4          2.917925
             ...
2092235    0.791762
2092236    0.395881
2092237    0.395881
2092238    1.187643
2092239    1.187643
Name: nt_nr_rpm_add, Length: 2092240, dtype: float64

In [12]:
species_cgs_df['nt_nr_rpm']

0          0.000000
1          0.000000
2          0.972642
3          0.972642
4          2.917925
             ...
2092235    0.000000
2092236    0.000000
2092237    0.000000
2092238    0.000000
2092239    0.000000
Name: nt_nr_rpm, Length: 2092240, dtype: float64

In [13]:
species_cgs_df['nt_nr_rpm'].isna().sum()

np.int64(0)

In [14]:
species_cgs_df['nt_nr_rpm_add'].isna().sum()

np.int64(0)

In [18]:
##this is the df with raw species column,used in the first pca script

pca_df_old=species_cgs_df[['name','nt_nr_rpm_add','sample_x']]
pca_df_old

,name,nt_nr_rpm_add,sample_x
0,Fusibacillus,7.781132,SRR18483737
1,Fusibacillus kribbianus,7.781132,SRR18483737
2,Xylocopilactobacillus,0.972642,SRR18483737
3,Xylocopilactobacillus apis,0.972642,SRR18483737
4,Fontisubflavum,2.917925,SRR18483737
...,...,...,...
2092235,Chloroherpetonaceae bacterium,0.791762,SRR27935984
2092236,non-genus-specific reads in family Desulfosarc...,0.395881,SRR27935984
2092237,Desulfosarcinaceae bacterium,0.395881,SRR27935984
2092238,non-genus-specific reads in family Candidatus ...,1.187643,SRR27935984
2092239,Candidatus Fermentithermobacillaceae bacterium,1.187643,SRR27935984

In [16]:
species_new_df=pd.read_excel(r'C:\Users\ssathees\OneDrive - Fred Hutchinson Cancer Research Center\Downloads\species_columns_mapping - Copy.xlsx',sheet_name='PR')
# Remove rows that are entirely NaN
species_new_df = species_new_df.dropna(how='all')
species_new_df

,name,n,sumrpm,Cleaned_SS,Cleaned[0],Cleaned_reviewed,check,Comments
0,'Allium porrum' stunting phytoplasma LeSt-Br01,6,9.8,Allium,Allium,Phytoplasma,False,Grouped as phytoplasma
1,'Boehmeria pannosa' witches'-broom phytoplasma,1,0.4,Boehmeria,Boehmeria,Phytoplasma,False,Grouped as phytoplasma
2,'Brassica napus' phytoplasma,2,1.2,Brassica,Brassica,Phytoplasma,False,Grouped as phytoplasma
3,'Burkholderia humi' Srinivasan et al. 2013,2,0.8,Burkholderia,Burkholderia,Burkholderia,True,NaN
4,'Catharanthus roseus' aster yellows phytoplasma,14,17.5,Catharanthus,Catharanthus,Phytoplasma,False,Grouped as phytoplasma
...,...,...,...,...,...,...,...,...
73012,Zymomonas mobilis,80,494.6,NaN,Zymomonas,Zymomonas,True,NaN
73013,Zymomonas sp.,14,18.3,NaN,Zymomonas,Zymomonas,True,NaN
73014,Zymoseptoria,44,189.8,NaN,Zymoseptoria,Zymoseptoria,True,NaN
73015,Zymoseptoria brevis,16,35.7,NaN,Zymoseptoria,Zymoseptoria,True,NaN
73016,Zymoseptoria tritici,40,154.1,NaN,Zymoseptoria,Zymoseptoria,True,NaN

In [19]:
pca_df_new=pd.merge(pca_df_old,species_new_df,on='name',how='left')
pca_df_new

,name,nt_nr_rpm_add,sample_x,n,sumrpm,Cleaned_SS,Cleaned[0],Cleaned_reviewed,check,Comments
0,Fusibacillus,7.781132,SRR18483737,60.0,117.6,NaN,Fusibacillus,Fusibacillus,True,NaN
1,Fusibacillus kribbianus,7.781132,SRR18483737,60.0,117.6,NaN,Fusibacillus,Fusibacillus,True,NaN
2,Xylocopilactobacillus,0.972642,SRR18483737,86.0,252.8,NaN,Xylocopilactobacillus,Xylocopilactobacillus,True,NaN
3,Xylocopilactobacillus apis,0.972642,SRR18483737,71.0,149.4,NaN,Xylocopilactobacillus,Xylocopilactobacillus,True,NaN
4,Fontisubflavum,2.917925,SRR18483737,60.0,93.1,NaN,Fontisubflavum,Fontisubflavum,True,NaN
...,...,...,...,...,...,...,...,...,...,...
2092235,Chloroherpetonaceae bacterium,0.791762,SRR27935984,51.0,114.9,NaN,Chloroherpetonaceae,Chloroherpetonaceae,True,NaN
2092236,non-genus-specific reads in family Desulfosarc...,0.395881,SRR27935984,31.0,29.8,NaN,non,Desulfosarcinaceae,False,Grouped as genus
2092237,Desulfosarcinaceae bacterium,0.395881,SRR27935984,31.0,29.8,NaN,Desulfosarcinaceae,Desulfosarcinaceae,True,NaN
2092238,non-genus-specific reads in family Candidatus ...,1.187643,SRR27935984,84.0,337.3,NaN,non,Candidatus Fermentithermobacillaceae,False,Grouped as genus
2092239,Candidatus Fermentithermobacillaceae bacterium,1.187643,SRR27935984,84.0,337.3,NaN,Candidatus,Candidatus Fermentithermobacillaceae,False,Grouped as genus

In [20]:
pca_df_new=pca_df_new[['Cleaned_reviewed','nt_nr_rpm_add','sample_x']]
pca_df_new=pca_df_new.rename(columns={'Cleaned_reviewed':'name'})
pca_df_new

                                         name  nt_nr_rpm_add     sample_x
0                                Fusibacillus       7.781132  SRR18483737
1                                Fusibacillus       7.781132  SRR18483737
2                       Xylocopilactobacillus       0.972642  SRR18483737
3                       Xylocopilactobacillus       0.972642  SRR18483737
4                              Fontisubflavum       2.917925  SRR18483737
...                                       ...            ...          ...
2092235                   Chloroherpetonaceae       0.791762  SRR27935984
2092236                    Desulfosarcinaceae       0.395881  SRR27935984
2092237                    Desulfosarcinaceae       0.395881  SRR27935984
2092238  Candidatus Fermentithermobacillaceae       1.187643  SRR27935984
2092239  Candidatus Fermentithermobacillaceae       1.187643  SRR27935984

[2092240 rows x 3 columns]

In [79]:
# Pivot the table: rows = samples, columns = species
pivot_df_new = pca_df_new.pivot_table(index='sample_x', columns='name', values='nt_nr_rpm_add', fill_value=0)
pivot_df_new

name,Aaosphaeria,Abacarus,Abditibacteriaceae,Abditibacteriales,Abditibacteriota,Abditibacterium,Abidjanvirus,Abies,Abiotrophia,Abortiporus,...,rumen,segmented,spirochete,subglacial,swine,uncultured,uncultured Candidatus,uncultured bacterium,unknown,x Festulolium
sample_x,,,,,,,,,,,,,,,,,,,,,
SRR18483737,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,46.686794,0.0,...,0.000000,0.0,0.0,0.0,0.000000,27.233963,1.296855,14.526465,31318.084908,0.0
SRR18483738,0.0,0.0,0.728222,0.0,0.364111,1.456444,0.0,0.0,9.102775,0.0,...,0.000000,0.0,0.0,0.0,0.000000,17701.619772,0.728222,7.930999,43197.277974,0.0
SRR18483750,0.0,0.0,0.000000,0.0,1.600129,0.000000,0.0,0.0,12.000970,0.0,...,0.000000,0.0,0.0,0.0,0.000000,17.901446,2.800226,9.637142,13691.639498,0.0
SRR18483755,0.0,0.0,0.000000,0.0,0.000000,1.270261,0.0,0.0,37.684400,0.0,...,0.000000,0.0,0.0,0.0,0.000000,9.018851,0.635130,23.807143,11350.414105,0.0
SRR18483759,0.0,0.0,0.000000,0.0,4.617079,0.000000,0.0,0.0,7.914993,0.0,...,0.659583,0.0,0.0,0.0,0.000000,18.648203,0.659583,16.673164,26703.207551,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SRR27935920,0.0,0.0,31.792934,0.0,43.013970,5.610518,0.0,0.0,68.822352,0.0,...,0.000000,0.0,0.0,0.0,0.000000,72.105544,2.805259,23.154518,18191.792436,0.0
SRR27935925,0.0,0.0,0.000000,0.0,0.797627,0.000000,0.0,0.0,68.276889,0.0,...,0.000000,0.0,0.0,0.0,0.398814,13.426725,1.794661,15.004904,25475.681239,0.0
SRR27935931,0.0,0.0,0.000000,0.0,0.521558,0.000000,0.0,0.0,13.299717,0.0,...,0.000000,0.0,0.0,0.0,0.000000,3.203853,1.564673,17.010800,11227.395262,0.0
SRR27935979,0.0,0.0,0.000000,0.0,1.005077,0.000000,0.0,0.0,1.340103,0.0,...,0.000000,0.0,0.0,0.0,0.000000,5.472086,0.000000,11.468187,1049.467945,0.0
SRR27935984,0.0,0.0,0.000000,0.0,0.395881,0.000000,0.0,0.0,5.806255,0.0,...,0.000000,0.0,0.0,0.0,0.000000,3.694890,0.000000,753.306354,10521.923858,0.0

In [80]:
SPECIES_ABUNDANCE_CSV = pivot_df_new  # rows: SRA_ID, cols: species (counts or rel. abund)
COGNITIVE_SCORES_CSV  = species_cgs_df[['sample_x','prop_correct']]   #SRA_ID, CognitiveScore
OUTPUT_DIR            = "pca_outputs_updated"
N_COMPONENTS          = 30 

os.makedirs(OUTPUT_DIR, exist_ok=True)

In [81]:
SPECIES_ABUNDANCE_CSV

name,Aaosphaeria,Abacarus,Abditibacteriaceae,Abditibacteriales,Abditibacteriota,Abditibacterium,Abidjanvirus,Abies,Abiotrophia,Abortiporus,...,rumen,segmented,spirochete,subglacial,swine,uncultured,uncultured Candidatus,uncultured bacterium,unknown,x Festulolium
sample_x,,,,,,,,,,,,,,,,,,,,,
SRR18483737,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,46.686794,0.0,...,0.000000,0.0,0.0,0.0,0.000000,27.233963,1.296855,14.526465,31318.084908,0.0
SRR18483738,0.0,0.0,0.728222,0.0,0.364111,1.456444,0.0,0.0,9.102775,0.0,...,0.000000,0.0,0.0,0.0,0.000000,17701.619772,0.728222,7.930999,43197.277974,0.0
SRR18483750,0.0,0.0,0.000000,0.0,1.600129,0.000000,0.0,0.0,12.000970,0.0,...,0.000000,0.0,0.0,0.0,0.000000,17.901446,2.800226,9.637142,13691.639498,0.0
SRR18483755,0.0,0.0,0.000000,0.0,0.000000,1.270261,0.0,0.0,37.684400,0.0,...,0.000000,0.0,0.0,0.0,0.000000,9.018851,0.635130,23.807143,11350.414105,0.0
SRR18483759,0.0,0.0,0.000000,0.0,4.617079,0.000000,0.0,0.0,7.914993,0.0,...,0.659583,0.0,0.0,0.0,0.000000,18.648203,0.659583,16.673164,26703.207551,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SRR27935920,0.0,0.0,31.792934,0.0,43.013970,5.610518,0.0,0.0,68.822352,0.0,...,0.000000,0.0,0.0,0.0,0.000000,72.105544,2.805259,23.154518,18191.792436,0.0
SRR27935925,0.0,0.0,0.000000,0.0,0.797627,0.000000,0.0,0.0,68.276889,0.0,...,0.000000,0.0,0.0,0.0,0.398814,13.426725,1.794661,15.004904,25475.681239,0.0
SRR27935931,0.0,0.0,0.000000,0.0,0.521558,0.000000,0.0,0.0,13.299717,0.0,...,0.000000,0.0,0.0,0.0,0.000000,3.203853,1.564673,17.010800,11227.395262,0.0
SRR27935979,0.0,0.0,0.000000,0.0,1.005077,0.000000,0.0,0.0,1.340103,0.0,...,0.000000,0.0,0.0,0.0,0.000000,5.472086,0.000000,11.468187,1049.467945,0.0
SRR27935984,0.0,0.0,0.000000,0.0,0.395881,0.000000,0.0,0.0,5.806255,0.0,...,0.000000,0.0,0.0,0.0,0.000000,3.694890,0.000000,753.306354,10521.923858,0.0

In [82]:
SPECIES_ABUNDANCE_CSV.to_csv('SPECIES_ABUNDANCE_CSV.csv')

In [83]:
def hellinger_transform(df_counts: pd.DataFrame) -> pd.DataFrame:
    """Row-normalize to relative abundance, then sqrt (Hellinger)."""
    rel = df_counts.div(df_counts.sum(axis=1).replace(0, np.nan), axis=0).fillna(0.0)
    return np.sqrt(rel)

In [84]:
abundance_df=pd.read_csv('SPECIES_ABUNDANCE_CSV.csv')
abundance_df

,sample_x,Aaosphaeria,Abacarus,Abditibacteriaceae,Abditibacteriales,Abditibacteriota,Abditibacterium,Abidjanvirus,Abies,Abiotrophia,...,rumen,segmented,spirochete,subglacial,swine,uncultured,uncultured Candidatus,uncultured bacterium,unknown,x Festulolium
0,SRR18483737,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,46.686794,...,0.000000,0.0,0.0,0.0,0.000000,27.233963,1.296855,14.526465,31318.084908,0.0
1,SRR18483738,0.0,0.0,0.728222,0.0,0.364111,1.456444,0.0,0.0,9.102775,...,0.000000,0.0,0.0,0.0,0.000000,17701.619772,0.728222,7.930999,43197.277974,0.0
2,SRR18483750,0.0,0.0,0.000000,0.0,1.600129,0.000000,0.0,0.0,12.000970,...,0.000000,0.0,0.0,0.0,0.000000,17.901446,2.800226,9.637142,13691.639498,0.0
3,SRR18483755,0.0,0.0,0.000000,0.0,0.000000,1.270261,0.0,0.0,37.684400,...,0.000000,0.0,0.0,0.0,0.000000,9.018851,0.635130,23.807143,11350.414105,0.0
4,SRR18483759,0.0,0.0,0.000000,0.0,4.617079,0.000000,0.0,0.0,7.914993,...,0.659583,0.0,0.0,0.0,0.000000,18.648203,0.659583,16.673164,26703.207551,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,SRR27935920,0.0,0.0,31.792934,0.0,43.013970,5.610518,0.0,0.0,68.822352,...,0.000000,0.0,0.0,0.0,0.000000,72.105544,2.805259,23.154518,18191.792436,0.0
95,SRR27935925,0.0,0.0,0.000000,0.0,0.797627,0.000000,0.0,0.0,68.276889,...,0.000000,0.0,0.0,0.0,0.398814,13.426725,1.794661,15.004904,25475.681239,0.0
96,SRR27935931,0.0,0.0,0.000000,0.0,0.521558,0.000000,0.0,0.0,13.299717,...,0.000000,0.0,0.0,0.0,0.000000,3.203853,1.564673,17.010800,11227.395262,0.0
97,SRR27935979,0.0,0.0,0.000000,0.0,1.005077,0.000000,0.0,0.0,1.340103,...,0.000000,0.0,0.0,0.0,0.000000,5.472086,0.000000,11.468187,1049.467945,0.0
98,SRR27935984,0.0,0.0,0.000000,0.0,0.395881,0.000000,0.0,0.0,5.806255,...,0.000000,0.0,0.0,0.0,0.000000,3.694890,0.000000,753.306354,10521.923858,0.0

In [85]:
abundance_df=abundance_df.rename(columns={'sample_x':'SRA_ID'})
abundance_df

,SRA_ID,Aaosphaeria,Abacarus,Abditibacteriaceae,Abditibacteriales,Abditibacteriota,Abditibacterium,Abidjanvirus,Abies,Abiotrophia,...,rumen,segmented,spirochete,subglacial,swine,uncultured,uncultured Candidatus,uncultured bacterium,unknown,x Festulolium
0,SRR18483737,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,46.686794,...,0.000000,0.0,0.0,0.0,0.000000,27.233963,1.296855,14.526465,31318.084908,0.0
1,SRR18483738,0.0,0.0,0.728222,0.0,0.364111,1.456444,0.0,0.0,9.102775,...,0.000000,0.0,0.0,0.0,0.000000,17701.619772,0.728222,7.930999,43197.277974,0.0
2,SRR18483750,0.0,0.0,0.000000,0.0,1.600129,0.000000,0.0,0.0,12.000970,...,0.000000,0.0,0.0,0.0,0.000000,17.901446,2.800226,9.637142,13691.639498,0.0
3,SRR18483755,0.0,0.0,0.000000,0.0,0.000000,1.270261,0.0,0.0,37.684400,...,0.000000,0.0,0.0,0.0,0.000000,9.018851,0.635130,23.807143,11350.414105,0.0
4,SRR18483759,0.0,0.0,0.000000,0.0,4.617079,0.000000,0.0,0.0,7.914993,...,0.659583,0.0,0.0,0.0,0.000000,18.648203,0.659583,16.673164,26703.207551,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,SRR27935920,0.0,0.0,31.792934,0.0,43.013970,5.610518,0.0,0.0,68.822352,...,0.000000,0.0,0.0,0.0,0.000000,72.105544,2.805259,23.154518,18191.792436,0.0
95,SRR27935925,0.0,0.0,0.000000,0.0,0.797627,0.000000,0.0,0.0,68.276889,...,0.000000,0.0,0.0,0.0,0.398814,13.426725,1.794661,15.004904,25475.681239,0.0
96,SRR27935931,0.0,0.0,0.000000,0.0,0.521558,0.000000,0.0,0.0,13.299717,...,0.000000,0.0,0.0,0.0,0.000000,3.203853,1.564673,17.010800,11227.395262,0.0
97,SRR27935979,0.0,0.0,0.000000,0.0,1.005077,0.000000,0.0,0.0,1.340103,...,0.000000,0.0,0.0,0.0,0.000000,5.472086,0.000000,11.468187,1049.467945,0.0
98,SRR27935984,0.0,0.0,0.000000,0.0,0.395881,0.000000,0.0,0.0,5.806255,...,0.000000,0.0,0.0,0.0,0.000000,3.694890,0.000000,753.306354,10521.923858,0.0

In [86]:
# Convert to numeric, force errors to NaN
#abundance_df = abundance_df.apply(pd.to_numeric, errors='coerce')

# Replace NaN with 0 (if they represent absence of counts)
#abundance_df = abundance_df.fillna(0)
# Compute pseudocount dynamically
#min_nonzero = abundance_df[abundance_df > 0].min().min()
#pseudo = min_nonzero / 10

In [87]:
# Find the smallest nonzero RPM in your data
#min_nonzero = abundance_df[abundance_df > 0].min().min()

# Suggest a pseudocount as 1/10th of that
#pseudo = min_nonzero / 10

#print("Minimum nonzero RPM:", min_nonzero)
#print("Suggested pseudocount:", pseudo)

In [88]:
from sklearn.decomposition import PCA
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [89]:
def run_pca(X: pd.DataFrame, n_components: int) -> tuple[pd.DataFrame, pd.DataFrame, PCA]:
    """Fit PCA and return (scores, loadings, pca_model)."""
    n_components = min(n_components, X.shape[1])
    pca = PCA(n_components=n_components)
    scores = pca.fit_transform(X.values)
    scores_df = pd.DataFrame(scores, index=X.index,
                             columns=[f"PC{i+1}" for i in range(pca.n_components_)])
    loadings_df = pd.DataFrame(pca.components_.T, index=X.columns,
                               columns=[f"PC{i+1}" for i in range(pca.n_components_)])
    return scores_df, loadings_df, pca

In [90]:
def correlate_pcs_with_trait(scores_df: pd.DataFrame, trait: pd.Series) -> pd.DataFrame:
    rows = []
    for pc in scores_df.columns:
        r_pea, p_pea = pearsonr(scores_df[pc], trait)
        r_spr, p_spr = spearmanr(scores_df[pc], trait)
        rows.append({
            "PC": pc,
            "Pearson_r": r_pea, "Pearson_p": p_pea,
            "Spearman_rho": r_spr, "Spearman_p": p_spr
        })
    return pd.DataFrame(rows)

In [91]:
def top_loading_species(loadings_df: pd.DataFrame, k=10) -> dict:
    """Return dict: PC -> DataFrame of top + and top - species by loading magnitude."""
    out = {}
    for pc in loadings_df.columns:
        s = loadings_df[pc].sort_values(ascending=False)
        top_pos = s.head(k).to_frame(name="loading")
        top_neg = s.tail(k).to_frame(name="loading")
        out[pc] = (top_pos, top_neg)
    return out

In [92]:
def quick_barplot_variance(pca: PCA, title: str, path: str):
    import matplotlib.pyplot as plt
    import numpy as np

    # Variance explained by each PC
    var_exp = pca.explained_variance_ratio_ * 100.0
    pcs = np.arange(1, pca.n_components_ + 1)

    plt.figure(figsize=(10, 6))
    bars = plt.bar(pcs, var_exp)

    # Add labels above each bar
    for bar, val in zip(bars, var_exp):
        plt.text(
            bar.get_x() + bar.get_width() / 2,   # x position (center of bar)
            bar.get_height() + 0.5,              # y position slightly above bar
            f"{val:.1f}%",                       # format as %
            ha="center", va="bottom", fontsize=8, rotation=90
        )

    plt.xlabel("Principal Component")
    plt.ylabel("% Variance Explained")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(path, dpi=150)
    plt.close()

In [93]:
def quick_scatter(scores_df: pd.DataFrame, trait: pd.Series, title: str, path: str,
                  x="PC1", y="PC2"):
    plt.figure()
    sc = plt.scatter(scores_df[x], scores_df[y], c=trait.values)
    plt.colorbar(sc, label=trait.name if trait.name else "Trait")
    plt.xlabel(x); plt.ylabel(y); plt.title(title)
    plt.tight_layout()
    plt.savefig(path, dpi=150)
    plt.close()

In [94]:
pivot_df_new

name,Aaosphaeria,Abacarus,Abditibacteriaceae,Abditibacteriales,Abditibacteriota,Abditibacterium,Abidjanvirus,Abies,Abiotrophia,Abortiporus,...,rumen,segmented,spirochete,subglacial,swine,uncultured,uncultured Candidatus,uncultured bacterium,unknown,x Festulolium
sample_x,,,,,,,,,,,,,,,,,,,,,
SRR18483737,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,46.686794,0.0,...,0.000000,0.0,0.0,0.0,0.000000,27.233963,1.296855,14.526465,31318.084908,0.0
SRR18483738,0.0,0.0,0.728222,0.0,0.364111,1.456444,0.0,0.0,9.102775,0.0,...,0.000000,0.0,0.0,0.0,0.000000,17701.619772,0.728222,7.930999,43197.277974,0.0
SRR18483750,0.0,0.0,0.000000,0.0,1.600129,0.000000,0.0,0.0,12.000970,0.0,...,0.000000,0.0,0.0,0.0,0.000000,17.901446,2.800226,9.637142,13691.639498,0.0
SRR18483755,0.0,0.0,0.000000,0.0,0.000000,1.270261,0.0,0.0,37.684400,0.0,...,0.000000,0.0,0.0,0.0,0.000000,9.018851,0.635130,23.807143,11350.414105,0.0
SRR18483759,0.0,0.0,0.000000,0.0,4.617079,0.000000,0.0,0.0,7.914993,0.0,...,0.659583,0.0,0.0,0.0,0.000000,18.648203,0.659583,16.673164,26703.207551,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SRR27935920,0.0,0.0,31.792934,0.0,43.013970,5.610518,0.0,0.0,68.822352,0.0,...,0.000000,0.0,0.0,0.0,0.000000,72.105544,2.805259,23.154518,18191.792436,0.0
SRR27935925,0.0,0.0,0.000000,0.0,0.797627,0.000000,0.0,0.0,68.276889,0.0,...,0.000000,0.0,0.0,0.0,0.398814,13.426725,1.794661,15.004904,25475.681239,0.0
SRR27935931,0.0,0.0,0.000000,0.0,0.521558,0.000000,0.0,0.0,13.299717,0.0,...,0.000000,0.0,0.0,0.0,0.000000,3.203853,1.564673,17.010800,11227.395262,0.0
SRR27935979,0.0,0.0,0.000000,0.0,1.005077,0.000000,0.0,0.0,1.340103,0.0,...,0.000000,0.0,0.0,0.0,0.000000,5.472086,0.000000,11.468187,1049.467945,0.0
SRR27935984,0.0,0.0,0.000000,0.0,0.395881,0.000000,0.0,0.0,5.806255,0.0,...,0.000000,0.0,0.0,0.0,0.000000,3.694890,0.000000,753.306354,10521.923858,0.0

In [95]:
pivot_df_new=pivot_df_new.reset_index()
pivot_df_new=pivot_df_new.rename(columns={'sample_x':'SRA_ID'})
pivot_df_new

name,SRA_ID,Aaosphaeria,Abacarus,Abditibacteriaceae,Abditibacteriales,Abditibacteriota,Abditibacterium,Abidjanvirus,Abies,Abiotrophia,...,rumen,segmented,spirochete,subglacial,swine,uncultured,uncultured Candidatus,uncultured bacterium,unknown,x Festulolium
0,SRR18483737,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,46.686794,...,0.000000,0.0,0.0,0.0,0.000000,27.233963,1.296855,14.526465,31318.084908,0.0
1,SRR18483738,0.0,0.0,0.728222,0.0,0.364111,1.456444,0.0,0.0,9.102775,...,0.000000,0.0,0.0,0.0,0.000000,17701.619772,0.728222,7.930999,43197.277974,0.0
2,SRR18483750,0.0,0.0,0.000000,0.0,1.600129,0.000000,0.0,0.0,12.000970,...,0.000000,0.0,0.0,0.0,0.000000,17.901446,2.800226,9.637142,13691.639498,0.0
3,SRR18483755,0.0,0.0,0.000000,0.0,0.000000,1.270261,0.0,0.0,37.684400,...,0.000000,0.0,0.0,0.0,0.000000,9.018851,0.635130,23.807143,11350.414105,0.0
4,SRR18483759,0.0,0.0,0.000000,0.0,4.617079,0.000000,0.0,0.0,7.914993,...,0.659583,0.0,0.0,0.0,0.000000,18.648203,0.659583,16.673164,26703.207551,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,SRR27935920,0.0,0.0,31.792934,0.0,43.013970,5.610518,0.0,0.0,68.822352,...,0.000000,0.0,0.0,0.0,0.000000,72.105544,2.805259,23.154518,18191.792436,0.0
95,SRR27935925,0.0,0.0,0.000000,0.0,0.797627,0.000000,0.0,0.0,68.276889,...,0.000000,0.0,0.0,0.0,0.398814,13.426725,1.794661,15.004904,25475.681239,0.0
96,SRR27935931,0.0,0.0,0.000000,0.0,0.521558,0.000000,0.0,0.0,13.299717,...,0.000000,0.0,0.0,0.0,0.000000,3.203853,1.564673,17.010800,11227.395262,0.0
97,SRR27935979,0.0,0.0,0.000000,0.0,1.005077,0.000000,0.0,0.0,1.340103,...,0.000000,0.0,0.0,0.0,0.000000,5.472086,0.000000,11.468187,1049.467945,0.0
98,SRR27935984,0.0,0.0,0.000000,0.0,0.395881,0.000000,0.0,0.0,5.806255,...,0.000000,0.0,0.0,0.0,0.000000,3.694890,0.000000,753.306354,10521.923858,0.0

In [96]:
# Keep only SRA_ID + all species columns
pivot_df_new = pivot_df_new.drop(columns=['level_0', 'index'], errors='ignore')
pivot_df_new

name,SRA_ID,Aaosphaeria,Abacarus,Abditibacteriaceae,Abditibacteriales,Abditibacteriota,Abditibacterium,Abidjanvirus,Abies,Abiotrophia,...,rumen,segmented,spirochete,subglacial,swine,uncultured,uncultured Candidatus,uncultured bacterium,unknown,x Festulolium
0,SRR18483737,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,46.686794,...,0.000000,0.0,0.0,0.0,0.000000,27.233963,1.296855,14.526465,31318.084908,0.0
1,SRR18483738,0.0,0.0,0.728222,0.0,0.364111,1.456444,0.0,0.0,9.102775,...,0.000000,0.0,0.0,0.0,0.000000,17701.619772,0.728222,7.930999,43197.277974,0.0
2,SRR18483750,0.0,0.0,0.000000,0.0,1.600129,0.000000,0.0,0.0,12.000970,...,0.000000,0.0,0.0,0.0,0.000000,17.901446,2.800226,9.637142,13691.639498,0.0
3,SRR18483755,0.0,0.0,0.000000,0.0,0.000000,1.270261,0.0,0.0,37.684400,...,0.000000,0.0,0.0,0.0,0.000000,9.018851,0.635130,23.807143,11350.414105,0.0
4,SRR18483759,0.0,0.0,0.000000,0.0,4.617079,0.000000,0.0,0.0,7.914993,...,0.659583,0.0,0.0,0.0,0.000000,18.648203,0.659583,16.673164,26703.207551,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,SRR27935920,0.0,0.0,31.792934,0.0,43.013970,5.610518,0.0,0.0,68.822352,...,0.000000,0.0,0.0,0.0,0.000000,72.105544,2.805259,23.154518,18191.792436,0.0
95,SRR27935925,0.0,0.0,0.000000,0.0,0.797627,0.000000,0.0,0.0,68.276889,...,0.000000,0.0,0.0,0.0,0.398814,13.426725,1.794661,15.004904,25475.681239,0.0
96,SRR27935931,0.0,0.0,0.000000,0.0,0.521558,0.000000,0.0,0.0,13.299717,...,0.000000,0.0,0.0,0.0,0.000000,3.203853,1.564673,17.010800,11227.395262,0.0
97,SRR27935979,0.0,0.0,0.000000,0.0,1.005077,0.000000,0.0,0.0,1.340103,...,0.000000,0.0,0.0,0.0,0.000000,5.472086,0.000000,11.468187,1049.467945,0.0
98,SRR27935984,0.0,0.0,0.000000,0.0,0.395881,0.000000,0.0,0.0,5.806255,...,0.000000,0.0,0.0,0.0,0.000000,3.694890,0.000000,753.306354,10521.923858,0.0

In [97]:
pivot_df_new.columns.name = None 
pivot_df_new.index.name = None
pivot_df_new

,SRA_ID,Aaosphaeria,Abacarus,Abditibacteriaceae,Abditibacteriales,Abditibacteriota,Abditibacterium,Abidjanvirus,Abies,Abiotrophia,...,rumen,segmented,spirochete,subglacial,swine,uncultured,uncultured Candidatus,uncultured bacterium,unknown,x Festulolium
0,SRR18483737,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,46.686794,...,0.000000,0.0,0.0,0.0,0.000000,27.233963,1.296855,14.526465,31318.084908,0.0
1,SRR18483738,0.0,0.0,0.728222,0.0,0.364111,1.456444,0.0,0.0,9.102775,...,0.000000,0.0,0.0,0.0,0.000000,17701.619772,0.728222,7.930999,43197.277974,0.0
2,SRR18483750,0.0,0.0,0.000000,0.0,1.600129,0.000000,0.0,0.0,12.000970,...,0.000000,0.0,0.0,0.0,0.000000,17.901446,2.800226,9.637142,13691.639498,0.0
3,SRR18483755,0.0,0.0,0.000000,0.0,0.000000,1.270261,0.0,0.0,37.684400,...,0.000000,0.0,0.0,0.0,0.000000,9.018851,0.635130,23.807143,11350.414105,0.0
4,SRR18483759,0.0,0.0,0.000000,0.0,4.617079,0.000000,0.0,0.0,7.914993,...,0.659583,0.0,0.0,0.0,0.000000,18.648203,0.659583,16.673164,26703.207551,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,SRR27935920,0.0,0.0,31.792934,0.0,43.013970,5.610518,0.0,0.0,68.822352,...,0.000000,0.0,0.0,0.0,0.000000,72.105544,2.805259,23.154518,18191.792436,0.0
95,SRR27935925,0.0,0.0,0.000000,0.0,0.797627,0.000000,0.0,0.0,68.276889,...,0.000000,0.0,0.0,0.0,0.398814,13.426725,1.794661,15.004904,25475.681239,0.0
96,SRR27935931,0.0,0.0,0.000000,0.0,0.521558,0.000000,0.0,0.0,13.299717,...,0.000000,0.0,0.0,0.0,0.000000,3.203853,1.564673,17.010800,11227.395262,0.0
97,SRR27935979,0.0,0.0,0.000000,0.0,1.005077,0.000000,0.0,0.0,1.340103,...,0.000000,0.0,0.0,0.0,0.000000,5.472086,0.000000,11.468187,1049.467945,0.0
98,SRR27935984,0.0,0.0,0.000000,0.0,0.395881,0.000000,0.0,0.0,5.806255,...,0.000000,0.0,0.0,0.0,0.000000,3.694890,0.000000,753.306354,10521.923858,0.0

In [98]:
pivot_df_new.to_csv('SPECIES_ABUNDANCE_CSV.csv',index=False)

In [99]:
COGNITIVE_SCORES_CSV.to_csv('COGNITIVE_SCORES_CSV',index=False)

In [100]:
cog = pd.read_csv('COGNITIVE_SCORES_CSV.csv')
cog

              SRA_ID  CognitiveScore
0        SRR18483737        0.777778
1        SRR18483737        0.777778
2        SRR18483737        0.777778
3        SRR18483737        0.777778
4        SRR18483737        0.777778
...              ...             ...
2092235  SRR27935984        0.666667
2092236  SRR27935984        0.666667
2092237  SRR27935984        0.666667
2092238  SRR27935984        0.666667
2092239  SRR27935984        0.666667

[2092240 rows x 2 columns]

In [101]:
# === CLEAN ALIGNMENT OF ABUNDANCE & COG TABLES ===
def norm_id(x: str) -> str:
    """Normalize sample IDs so they match across files."""
    x = str(x).strip()
    x = x.split('/')[-1].split('\\')[-1]  # drop paths
    x = x.split('.')[0]                   # drop extensions (e.g., .fastq.gz)
    return x

def require_cols(df: pd.DataFrame, needed: list, dfname: str = "DataFrame"):
    missing = [c for c in needed if c not in df.columns]
    if missing:
        raise ValueError(f"{dfname} is missing columns: {missing}. "
                         f"Has: {list(df.columns)[:10]}...")

In [102]:
# 0) Expect: abundance_df has a column 'SRA_ID' + species columns.
#            cog has columns 'SRA_ID' and 'CognitiveScore'.
require_cols(abundance_df, ["SRA_ID"], "abundance_df")
require_cols(cog, ["SRA_ID", "CognitiveScore"], "cog")

In [103]:
# 1) Normalize IDs on both sides
abundance_df = abundance_df.copy()
cog = cog.copy()
abundance_df["SRA_ID"] = abundance_df["SRA_ID"].map(norm_id)
cog["SRA_ID"]          = cog["SRA_ID"].map(norm_id)

In [104]:
# 2) Drop obvious bad rows / duplicates, then set index
abundance_df = (abundance_df
                .dropna(subset=["SRA_ID"])
                .drop_duplicates(subset=["SRA_ID"])
                .set_index("SRA_ID"))

In [105]:
cog = (cog
       .dropna(subset=["SRA_ID", "CognitiveScore"])
       .drop_duplicates(subset=["SRA_ID"])
       .set_index("SRA_ID"))

In [106]:
# 3) Align by overlapping SRA_IDs
common = abundance_df.index.intersection(cog.index)
print("overlap n =", len(common))
if len(common) == 0:
    # helpful diagnostics
    print("Example IDs (abundance):", list(abundance_df.index[:5]))
    print("Example IDs (cog):", list(cog.index[:5]))
    raise ValueError("No overlapping SRA_IDs after normalization. "
                     "Inspect ID formats and the norm_id() function.")

abundance_df = abundance_df.loc[common].sort_index()
trait = cog.loc[common, "CognitiveScore"].astype(float)

print("aligned abundance_df shape:", abundance_df.shape)
print("aligned trait shape:", trait.shape)

overlap n = 93
aligned abundance_df shape: (93, 10850)
aligned trait shape: (93,)

In [107]:
# 4) Optional pruning: drop species that are zero in all aligned samples
nonzero_cols = (abundance_df > 0).any(axis=0)
abundance_df = abundance_df.loc[:, nonzero_cols]
print("columns after dropping all-zero species:", abundance_df.shape[1])

columns after dropping all-zero species: 10729

In [108]:
# === ready for tb-PCA (Hellinger -> PCA) ===
def hellinger_transform(df_counts: pd.DataFrame) -> pd.DataFrame:
    rel = df_counts.div(df_counts.sum(axis=1).replace(0, np.nan), axis=0).fillna(0.0)
    return np.sqrt(rel)

In [109]:
from sklearn.decomposition import PCA
from scipy.stats import pearsonr, spearmanr

In [110]:
X_hel = hellinger_transform(abundance_df)
n_components = min(10, X_hel.shape[1])
pca = PCA(n_components=n_components)
#scores = pd.DataFrame(pca.fit_transform(X_hel), index=X_hel.index,
                   #   columns=[f"PC{i+1}" for i in range(pca.n_components_)])
#loadings = pd.DataFrame(pca.components_.T, index=X_hel.columns,
                       # columns=scores.columns)

In [111]:
#2) PCA on Hellinger data
scores_hel, loadings_hel, pca_hel = run_pca(X_hel, N_COMPONENTS)

In [112]:
# 3) PC ~ cognition correlations (works now)
corr_hel = correlate_pcs_with_trait(scores_hel, trait)
corr_hel

      PC  Pearson_r  Pearson_p  Spearman_rho  Spearman_p
0    PC1   0.044943   0.668821      0.062787    0.549911
1    PC2  -0.050931   0.627792     -0.241370    0.019765
2    PC3  -0.305696   0.002884     -0.283268    0.005934
3    PC4  -0.073217   0.485510     -0.073531    0.483634
4    PC5  -0.010750   0.918539     -0.007967    0.939587
5    PC6  -0.046758   0.656273     -0.037250    0.722971
6    PC7   0.026428   0.801456     -0.000548    0.995839
7    PC8   0.061373   0.558944      0.067862    0.518062
8    PC9  -0.017101   0.870755     -0.096748    0.356241
9   PC10   0.056858   0.588270      0.024530    0.815452
10  PC11  -0.078917   0.452092     -0.080537    0.442836
11  PC12   0.039583   0.706389      0.063357    0.546283
12  PC13   0.041053   0.696008      0.013478    0.897972
13  PC14  -0.111757   0.286192     -0.118260    0.258898
14  PC15  -0.090149   0.390140     -0.114453    0.274652
15  PC16   0.136389   0.192371      0.116555    0.265874
16  PC17   0.014326   0.891587      0.077383    0.460958
17  PC18  -0.152763   0.143778     -0.167456    0.108626
18  PC19   0.052285   0.618670      0.024328    0.816950
19  PC20   0.069440   0.508360      0.044030    0.675163
20  PC21  -0.128792   0.218565     -0.164415    0.115290
21  PC22  -0.129901   0.214591     -0.079718    0.447500
22  PC23   0.099581   0.342264      0.094931    0.365389
23  PC24   0.038345   0.715170     -0.036154    0.730808
24  PC25  -0.033303   0.751318     -0.052688    0.615965
25  PC26   0.099126   0.344487      0.059273    0.572502
26  PC27   0.096819   0.355886      0.033008    0.753449
27  PC28  -0.125155   0.231957     -0.129816    0.214894
28  PC29   0.166900   0.109821      0.083555    0.425873
29  PC30  -0.006092   0.953786     -0.041868    0.690282

In [113]:
print("X_hel shape:", X_hel.shape)                 # samples x species
print("scores_hel shape:", scores_hel.shape)       # samples x PCs
print("trait shape:", trait.shape)                 # samples
assert scores_hel.shape[0] == trait.shape[0], "Samples mismatch between scores and trait!"

X_hel shape: (93, 10729)
scores_hel shape: (93, 30)
trait shape: (93,)

In [127]:
# exports
scores_hel.to_csv(os.path.join(OUTPUT_DIR, "tbPCA_scores.csv"))
loadings_hel.to_csv(os.path.join(OUTPUT_DIR, "tbPCA_loadings.csv"))
corr_hel.to_csv(os.path.join(OUTPUT_DIR, "tbPCA_cognition_correlations.csv"), index=False)

In [128]:
# plots
quick_barplot_variance(pca_hel,
                       "tb-PCA (Hellinger) — Variance Explained",
                       os.path.join(OUTPUT_DIR, "tbPCA_variance.png"))
quick_scatter(scores_hel, trait,
              "tb-PCA PC1 vs PC2 (colored by CognitiveScore)",
              os.path.join(OUTPUT_DIR, "tbPCA_PC1_PC2_cognition.png"))

In [129]:
# top contributing species per PC
tops_hel = top_loading_species(loadings_hel, k=30)
with open(os.path.join(OUTPUT_DIR, "tbPCA_top_loading_species.txt"), "w") as f:
    for pc, (pos, neg) in tops_hel.items():
        f.write(f"\n=== {pc} ===\nTop +loadings:\n")
        f.write(pos.to_string())
        f.write("\nTop -loadings:\n")
        f.write(neg.to_string())
        f.write("\n")

In [130]:
quick_scatter(scores_hel, trait,
              "tb-PCA PC3 vs PC1 (colored by CognitiveScore)",
              os.path.join(OUTPUT_DIR, "tbPCA_PC3_PC1_cognition.png"),
              x="PC3", y="PC1")

In [132]:
tops_hel= top_loading_species(loadings_hel, k=30)

In [134]:
def plot_cumulative_variance(pca, title, path):
    import numpy as np
    import matplotlib.pyplot as plt

    # cumulative variance from the argument `pca`, not hardcoded
    cumvar = np.cumsum(pca.explained_variance_ratio_) * 100

    plt.figure(figsize=(6,4))
    plt.plot(range(1, len(cumvar)+1), cumvar, marker='o')
    plt.axhline(90, color='r', linestyle='--', label="90% threshold")
    plt.xlabel("Principal Component")
    plt.ylabel("Cumulative Variance Explained (%)")
    plt.title(title)
    plt.legend()
    plt.tight_layout()
    plt.savefig(path, dpi=150)
    plt.close()

    # PCs needed for ~90%
    n_pcs_90 = np.argmax(cumvar >= 90) + 1 if np.any(cumvar >= 90) else None
    if n_pcs_90:
        print(f"≈90% of variance is explained by the first {n_pcs_90} PCs.")
    else:
        print("Even with all PCs, variance explained is <90%.")
plot_cumulative_variance(
    pca_hel,  # or pca_clr
    "Cumulative Variance Explained (Hellinger)", 
    os.path.join(OUTPUT_DIR, "cumvar_tbPCA.png")
)

Even with all PCs, variance explained is <90%.

In [122]:
#Fit regression line
import os
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import linregress  # if you don't have SciPy, see the polyfit fallback below

# x and y
x = scores_hel["PC3"].to_numpy()
y = np.asarray(trait.values, dtype=float)

# drop NaNs just in case
mask = np.isfinite(x) & np.isfinite(y)
x, y = x[mask], y[mask]

# fit y = m*x + b
res = linregress(x, y)  # res.slope, res.intercept, res.rvalue, res.pvalue
x_line = np.linspace(x.min(), x.max(), 200)
y_line = res.slope * x_line + res.intercept

# plot
plt.figure()
sc = plt.scatter(x, y, c=y, cmap="viridis")
plt.plot(x_line, y_line, linewidth=2, color="black",
         label=f'y = {res.slope:.3f}x + {res.intercept:.3f} '
               f'(R²={res.rvalue**2:.3f}, p={res.pvalue:.2e})')
plt.legend()

plt.colorbar(sc, label=trait.name if trait.name else "CognitiveScore")
plt.xlabel("PC3")
plt.ylabel("CognitiveScore")
plt.title("PC3 vs CognitiveScore")
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "tbPCA_PC3_cognition_with_regline.png"), dpi=150)
plt.close()